Objetivo 3
agr8/Planner-IV pull request #21
Opened 2021-12-08 00:23 UTC by agr8

- Añadida la **clave _automatizar_** y las **subclaves _fichero_** y **_orden_** al fichero _**iv.yaml**_
- Añadido el fichero **_package.json_** al proyecto. Este se ha creado siguiendo la [documentación](https://docs.npmjs.com/cli/v7/configuring-npm/package-json).
- Añadido en el _**README.md**_ las órdenes disponibles hasta este momento.
- Se ha incluido en la **_documentación adicional_** la **justificación** de la elección de **TypeScript** como lenguaje, así como la justificación de la elección de **npm** como gestor de dependencias y de tareas.
- Se ha creado un **issue** #20 asociado al [Milestone 1](https://github.com/agr8/Planner-IV/milestone/3) para realizar este objetivo.

2021-12-08 09:26 UTC, agr8 commented
Listo para revisión @JJ

2021-12-08 12:16 UTC, JJ requested changes
El milestone al que esté asignado tiene que incluir esto como parte del PMV.

2021-12-08 12:58 UTC, agr8 commented
> El milestone al que esté asignado tiene que incluir esto como parte del PMV.

Cierto, acabo de reestructurarlo. He creado un [nuevo milestone](https://github.com/agr8/Planner-IV/milestone/4) y le he asignado el issue #20. También he asignado este PR #21 al [milestone 4](https://github.com/agr8/Planner-IV/milestone/4). Acabo de entender que lo que había hecho antes no tenía sentido, lo siento :sweat_smile:

2021-12-09 18:33 UTC, JJ approved these changes
La comparación está bien hecha, pero te ha faltado el criterio de búsqueda. En todo caso, esencialmente has pasado y no quiero retrasarte más.

2021-12-09 18:33 UTC, JJ commented on docs/info.md
> +
Me temo que estás dejando fuera gestores de tareas específicos de TS/JS tales como grunt y gulp.

2021-12-10 08:02 UTC, merged